version: '3.3'
services:
    mongo:
        image: mongo
        container_name: dkrcomp-mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=bdung
        restart: always
        ports:
            - '27017:27017'
        logging:
            options:
                max-size: 1g